name: Build, Lint, and Test

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          cache-node-modules: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - name: Build
        run: yarn build
      - name: Upload Snap build artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-${{ runner.os }}-${{ github.sha }}
          path: ./packages/snap/dist
          retention-days: 1

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - name: Lint
        run: yarn lint

  e2e-test:
    name: End-to-end Test
    runs-on: ubuntu-latest
    needs:
      - prepare
      - build
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - name: Download Snap build artifact
        uses: actions/download-artifact@v4
        with:
          name: snap-${{ runner.os }}-${{ github.sha }}
          path: ./packages/snap/dist
      - name: Run e2e tests
        run: yarn workspace @yigitkara/chain-guardian run test
